name = "superrrect"
main = "TgMultiAutoReact.ts"
compatibility_date = "2025-09-16"
workers_dev = true

# Provide BOT_TOKENS as a JSON array or comma-separated string;
# You Can Add Multiple Unlimited Bot Tokens ( Make Sure The All Tokens Are Correct and Added in The Same Format) 

[vars]
BOT_TOKENS = """[
  "8791225468:AAFASDVtt6Sfwyyy9N6Dc0AF67C0GaHeuig",
  "8862859175:AAHXg6VWXoGmRNnxg_0vvjVR-67adLSZb8w",
  "8630569133:AAFhVR749zo0CtGL6fV7Hjh7fElSCLBVULI",
  "8816821317:AAEMl3CVG-ZNuKb0uDu5JG237GeCm0p0284",
  "8771423236:AAEBjT2MNLETNlST1mc8H07AnAKwhTQstzM",
  "8574160093:AAF7pVAzbQB6e0vix1GSoPQWRkBXebw9gLQ",
  "7792734971:AAFFSlDvA3b0rgxBQpQc1eRuvPpAV2C74TM",
  "8941655652:AAHjhQdM4AacWnrZ1wxTPMmeZcB9NNQvAvM",
  "8909700325:AAEYgecRSC9iAlSK6CJFuv9BPAJPVANgwkw",
  "8944410586:AAFDHRUI6040zSrCY9OnyLZToK1ylMi7a5U",
  "8927343377:AAGomaVoNoWci33H95BXmP4GTjTJMUqMexo",
  "7952374063:AAEeyzRLYS3v9Gsps19XP9XsDbo0Xo4Kj3o",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  "Bot Token 5",
  
  "Last Bot Token"
]"""

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



