name = "superrrect"
main = "TgMultiAutoReact.ts"
compatibility_date = "2025-09-16"
workers_dev = true

# Provide BOT_TOKENS as a JSON array or comma-separated string;
# You Can Add Multiple Unlimited Bot Tokens ( Make Sure The All Tokens Are Correct and Added in The Same Format) 

[vars]
BOT_TOKENS = """[
  "8791225468:AAFASDVtt6Sfwyyy9N6Dc0AF67C0GaHeuig",
  "8862859175:AAHXg6VWXoGmRNnxg_0vvjVR-67adLSZb8w",
  "8630569133:AAFhVR749zo0CtGL6fV7Hjh7fElSCLBVULI",
  "Bot Token 4",
  "Bot Token 5",
  
  "Last Bot Token"
]"""

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



